<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Schéma initial de YoutubeBoost.
 */
final class Version20260912164355 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Schéma initial : chaîne, catalogue, statistiques quotidiennes, analyses, propositions de miniatures, relances, réglages, quota et jobs.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE analysis (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, summary TEXT NOT NULL, promise TEXT NOT NULL, angles JSON NOT NULL, model VARCHAR(64) NOT NULL, transcript_used BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, video_id VARCHAR(32) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_analysis_video ON analysis (video_id)');
        $this->addSql('CREATE TABLE channel (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, youtube_id VARCHAR(64) NOT NULL, title VARCHAR(255) NOT NULL, uploads_playlist_id VARCHAR(64) NOT NULL, thumbnail_url VARCHAR(512) DEFAULT NULL, encrypted_refresh_token TEXT NOT NULL, encrypted_access_token TEXT DEFAULT NULL, access_token_expires_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, scopes JSON DEFAULT \'[]\' NOT NULL, connected_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, last_synced_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, analytics_available_until DATE DEFAULT NULL, reporting_job_id VARCHAR(128) DEFAULT NULL, last_imported_report_id VARCHAR(128) DEFAULT NULL, reconnection_required BOOLEAN DEFAULT false NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A2F98E47BB7E40D1 ON channel (youtube_id)');
        $this->addSql('CREATE TABLE daily_stat (stat_date DATE NOT NULL, views INT DEFAULT 0 NOT NULL, estimated_minutes_watched INT DEFAULT 0 NOT NULL, average_view_duration INT DEFAULT NULL, average_view_percentage DOUBLE PRECISION DEFAULT NULL, impressions INT DEFAULT NULL, click_through_rate DOUBLE PRECISION DEFAULT NULL, video_id VARCHAR(32) NOT NULL, PRIMARY KEY (video_id, stat_date))');
        $this->addSql('CREATE INDEX IDX_64BEE0B429C1004E ON daily_stat (video_id)');
        $this->addSql('CREATE TABLE job (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(32) NOT NULL, status VARCHAR(16) NOT NULL, subject_id VARCHAR(64) DEFAULT NULL, done INT DEFAULT 0 NOT NULL, total INT DEFAULT 0 NOT NULL, progress INT DEFAULT 0 NOT NULL, step VARCHAR(255) DEFAULT NULL, error_message TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, finished_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_job_type_status ON job (type, status)');
        $this->addSql('CREATE TABLE quota_usage (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, quota_day DATE NOT NULL, endpoint VARCHAR(32) NOT NULL, cost INT NOT NULL, recorded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_quota_usage_day ON quota_usage (quota_day)');
        $this->addSql('CREATE TABLE reference_photo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, path VARCHAR(255) NOT NULL, angle VARCHAR(16) NOT NULL, label VARCHAR(128) NOT NULL, mime_type VARCHAR(64) NOT NULL, byte_size INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_C216E408B548B0F ON reference_photo (path)');
        $this->addSql('CREATE TABLE relaunch (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, archived_path VARCHAR(255) NOT NULL, archived_mime_type VARCHAR(64) NOT NULL, previous_thumbnail_url VARCHAR(512) DEFAULT NULL, applied_image_path VARCHAR(255) DEFAULT NULL, status VARCHAR(16) NOT NULL, snapshot_before JSON NOT NULL, snapshot_at14 JSON DEFAULT NULL, snapshot_at28 JSON DEFAULT NULL, verdict_at14 VARCHAR(16) DEFAULT NULL, verdict_at28 VARCHAR(16) DEFAULT NULL, applied_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, reverted_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, video_id VARCHAR(32) NOT NULL, proposal_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_relaunch_video ON relaunch (video_id)');
        $this->addSql('CREATE INDEX idx_relaunch_status ON relaunch (status)');
        $this->addSql('CREATE INDEX IDX_9AACDC90F4792058 ON relaunch (proposal_id)');
        $this->addSql('CREATE TABLE setting (name VARCHAR(64) NOT NULL, value JSON DEFAULT NULL, PRIMARY KEY (name))');
        $this->addSql('CREATE TABLE thumbnail_proposal (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, angle_index INT NOT NULL, overlay_text VARCHAR(64) NOT NULL, reference_angle VARCHAR(16) NOT NULL, prompt TEXT NOT NULL, status VARCHAR(16) NOT NULL, image_path VARCHAR(255) DEFAULT NULL, byte_size INT DEFAULT NULL, model VARCHAR(64) DEFAULT NULL, error_message TEXT DEFAULT NULL, iteration_instruction TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, generated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, applied_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, analysis_id INT NOT NULL, video_id VARCHAR(32) NOT NULL, parent_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_proposal_video ON thumbnail_proposal (video_id)');
        $this->addSql('CREATE INDEX idx_proposal_analysis ON thumbnail_proposal (analysis_id)');
        $this->addSql('CREATE INDEX IDX_961EF981727ACA70 ON thumbnail_proposal (parent_id)');
        $this->addSql('CREATE TABLE transcript (source VARCHAR(16) NOT NULL, language VARCHAR(16) NOT NULL, text TEXT NOT NULL, unavailable_reason VARCHAR(255) DEFAULT NULL, fetched_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, video_id VARCHAR(32) NOT NULL, PRIMARY KEY (video_id))');
        $this->addSql('CREATE TABLE video (youtube_id VARCHAR(32) NOT NULL, title VARCHAR(255) NOT NULL, description TEXT NOT NULL, published_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, duration_seconds INT NOT NULL, type VARCHAR(16) NOT NULL, type_source VARCHAR(16) NOT NULL, visibility VARCHAR(16) NOT NULL, view_count INT NOT NULL, like_count INT NOT NULL, comment_count INT NOT NULL, captions_available BOOLEAN NOT NULL, language VARCHAR(16) DEFAULT NULL, custom_thumbnail BOOLEAN DEFAULT NULL, score INT DEFAULT 0 NOT NULL, signals JSON DEFAULT \'{}\' NOT NULL, score_reliable BOOLEAN DEFAULT false NOT NULL, scored_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_analyzed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, stats_synced_until DATE DEFAULT NULL, relaunch_state VARCHAR(16) DEFAULT \'none\' NOT NULL, last_relaunch_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, synced_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, thumbnails_images JSON DEFAULT \'{}\' NOT NULL, PRIMARY KEY (youtube_id))');
        $this->addSql('CREATE INDEX idx_video_score ON video (score)');
        $this->addSql('CREATE INDEX idx_video_published_at ON video (published_at)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE analysis ADD CONSTRAINT FK_33C73029C1004E FOREIGN KEY (video_id) REFERENCES video (youtube_id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE daily_stat ADD CONSTRAINT FK_64BEE0B429C1004E FOREIGN KEY (video_id) REFERENCES video (youtube_id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE relaunch ADD CONSTRAINT FK_9AACDC9029C1004E FOREIGN KEY (video_id) REFERENCES video (youtube_id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE relaunch ADD CONSTRAINT FK_9AACDC90F4792058 FOREIGN KEY (proposal_id) REFERENCES thumbnail_proposal (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thumbnail_proposal ADD CONSTRAINT FK_961EF9817941003F FOREIGN KEY (analysis_id) REFERENCES analysis (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thumbnail_proposal ADD CONSTRAINT FK_961EF98129C1004E FOREIGN KEY (video_id) REFERENCES video (youtube_id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE thumbnail_proposal ADD CONSTRAINT FK_961EF981727ACA70 FOREIGN KEY (parent_id) REFERENCES thumbnail_proposal (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE transcript ADD CONSTRAINT FK_A8F617C329C1004E FOREIGN KEY (video_id) REFERENCES video (youtube_id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE analysis DROP CONSTRAINT FK_33C73029C1004E');
        $this->addSql('ALTER TABLE daily_stat DROP CONSTRAINT FK_64BEE0B429C1004E');
        $this->addSql('ALTER TABLE relaunch DROP CONSTRAINT FK_9AACDC9029C1004E');
        $this->addSql('ALTER TABLE relaunch DROP CONSTRAINT FK_9AACDC90F4792058');
        $this->addSql('ALTER TABLE thumbnail_proposal DROP CONSTRAINT FK_961EF9817941003F');
        $this->addSql('ALTER TABLE thumbnail_proposal DROP CONSTRAINT FK_961EF98129C1004E');
        $this->addSql('ALTER TABLE thumbnail_proposal DROP CONSTRAINT FK_961EF981727ACA70');
        $this->addSql('ALTER TABLE transcript DROP CONSTRAINT FK_A8F617C329C1004E');
        $this->addSql('DROP TABLE analysis');
        $this->addSql('DROP TABLE channel');
        $this->addSql('DROP TABLE daily_stat');
        $this->addSql('DROP TABLE job');
        $this->addSql('DROP TABLE quota_usage');
        $this->addSql('DROP TABLE reference_photo');
        $this->addSql('DROP TABLE relaunch');
        $this->addSql('DROP TABLE setting');
        $this->addSql('DROP TABLE thumbnail_proposal');
        $this->addSql('DROP TABLE transcript');
        $this->addSql('DROP TABLE video');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
