; https://symfony.com/doc/current/performance.html#use-the-opcache-class-preloading
opcache.preload_user = www-data
opcache.preload = /app/config/preload.php
; The cache is built at image build time and never changes at runtime.
opcache.validate_timestamps = 0
